### ISSUE TITLE
Error in #authenticate when password contains an ampersand

### ISSUE THREAD

**Issue by lavaturtle** [javierjulio/salesforce_bulk#22]
When the supplied password contains an ampersand, we get an error back from the server:

```
> require 'salesforce_bulk'
> client = SalesforceBulk::Client.new(username: 'foo', password: "123&abc^456")
> client.authenticate

SalesforceBulk::SalesforceError (UNKNOWN_EXCEPTION: The reference to entity "abc" must end with the ';' delimiter.)
```

I think when we plug the password into the body on https://github.com/javierjulio/salesforce_bulk/blob/v4.0.0/lib/salesforce_bulk/client.rb#L50 we probably need to escape reserved XML characters (`&`, `"`, `'`, `<`, and `>`). There may be some appropriate library to handle this.

(I'm using version 4.0.0 of the gem)

**Comment by javierjulio** [comment]
@lavaturtle that makes sense, thanks. This should be simple enough to [fix by just using the `encode` method](https://stackoverflow.com/a/7573833). I didn't know this about the `encode` method. It does work as expected:
```
>> "123&abc^456".encode(xml: :text)
=> "123&amp;abc^456"
```
I'd be open to a PR with the appropriate fix if you want to create one. Thanks for reporting!
